repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.7.0
    hooks:
      - id: isort
        name: isort-model
        entry: isort ./model/src
        pass_filenames: false

  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
        name: black-model
        entry: black ./model/src
        pass_filenames: false

  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        name: flake8-model
        entry: flake8 ./model/src
        pass_filenames: false

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        name: mypy-model
        entry: mypy --ignore-missing-imports ./model/src
        pass_filenames: false
