name: Test model package
on: push

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Check out Git repo
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        working-directory: ./model
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: make create_venv

      - name: Lint with pre-commit
        run: make lint

      - name: Test with pytest
        run: make unittests
